/*
 * THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Copyright (C) 2022 Trusted Objects. All rights reserved.
 */

/**
 * Data below depends on TO-Protect binary delivery, and should not be edited
 * by hand.
 */

#ifndef _TOP_STORAGE_ALLOC_H_
#define _TOP_STORAGE_ALLOC_H_

/* TO-Protect RAM and NVM data size */
#define TOP_NVM_CLEAR_DATA_SIZE 2524u
#define TOP_NVM_SECRET_DATA_SIZE 856u
#define TOP_RAM_DATA_SIZE 2984u

/* TO-Protect Secure Storage footprints */
#define TOP_SECURE_STORAGE_NVM_FOOTPRINT 6816u
#define TOP_SECURE_STORAGE_RAM_FOOTPRINT 5144u

/* TO-Protect Secure Storage map */
#define TOP_SECURE_STORAGE_NVM_SECRET_OFFSET 0
#define TOP_SECURE_STORAGE_NVM_CLEAR_OFFSET 4288u

#define TOP_INTERNAL_CTX_SIZE 104u

#endif // _TOP_STORAGE_ALLOC_H_
