/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x01000E0CU /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x80000000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< Signal name */

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_EMC_40 (coord A7), ENET_MDC */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_MDC_PERIPHERAL                                  ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_MDC_SIGNAL                                  enet_mdc   /*!< Signal name */

/* GPIO_EMC_41 (coord C7), ENET_MDIO */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_MDIO_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_MDIO_SIGNAL                                enet_mdio   /*!< Signal name */

/* GPIO_B1_10 (coord B13), ENET_TX_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TX_CLK_PERIPHERAL                               ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TX_CLK_SIGNAL                           enet_ref_clk   /*!< Signal name */

/* GPIO_B1_04 (coord E12), ENET_RXD0 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXD0_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXD0_SIGNAL                             enet_rx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RXD0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_B1_05 (coord D12), ENET_RXD1 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXD1_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXD1_SIGNAL                             enet_rx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_RXD1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_B1_06 (coord C12), ENET_CRS_DV */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_CRS_DV_PERIPHERAL                               ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_CRS_DV_SIGNAL                             enet_rx_en   /*!< Signal name */

/* GPIO_B1_11 (coord C13), ENET_RXER */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_RXER_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_RXER_SIGNAL                               enet_rx_er   /*!< Signal name */

/* GPIO_B1_07 (coord B12), ENET_TXD0 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXD0_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXD0_SIGNAL                             enet_tx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_TXD0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_B1_08 (coord A12), ENET_TXD1 */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXD1_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXD1_SIGNAL                             enet_tx_data   /*!< Signal name */
#define BOARD_INITPINS_ENET_TXD1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_B1_09 (coord A13), ENET_TXEN */
/* Routed pin properties */
#define BOARD_INITPINS_ENET_TXEN_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITPINS_ENET_TXEN_SIGNAL                               enet_tx_en   /*!< Signal name */

/* GPIO_AD_B0_10 (coord G13), JTAG_TDO/J21[13]/INT1_COMBO/ENET_INT/J22[6]/U32[11] */
/* Routed pin properties */
#define BOARD_INITPINS_INT1_COMBO_PERIPHERAL                               GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_INT1_COMBO_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_INT1_COMBO_CHANNEL                                    10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INT1_COMBO_GPIO                                     GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_INT1_COMBO_GPIO_PIN                                   10U   /*!< GPIO pin number */
#define BOARD_INITPINS_INT1_COMBO_GPIO_PIN_MASK                      (1U << 10U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_INT1_COMBO_PORT                                     GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_INT1_COMBO_PIN                                        10U   /*!< PORT pin number */
#define BOARD_INITPINS_INT1_COMBO_PIN_MASK                           (1U << 10U)   /*!< PORT pin mask */

/* GPIO_AD_B1_03 (coord M12), SPDIF_IN/J22[8] */
/* Routed pin properties */
#define BOARD_INITPINS_Meter_RX_PERIPHERAL                               LPUART2   /*!< Peripheral name */
#define BOARD_INITPINS_Meter_RX_SIGNAL                                        RX   /*!< Signal name */

/* GPIO_AD_B1_02 (coord L11), SPDIF_OUT/J22[7] */
/* Routed pin properties */
#define BOARD_INITPINS_Meter_TX_PERIPHERAL                               LPUART2   /*!< Peripheral name */
#define BOARD_INITPINS_Meter_TX_SIGNAL                                        TX   /*!< Signal name */

/* GPIO_B0_00 (coord D7), LCDIF_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_CLK_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_CLK_SIGNAL                                lcdif_clk   /*!< Signal name */

/* GPIO_B0_04 (coord C8), LCDIF_D0/BT_CFG[0] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D0_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D0_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_B1_03 (coord D11), LCDIF_D15 */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D15_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D15_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D15_CHANNEL                                     15U   /*!< Signal channel */

/* GPIO_B1_02 (coord C11), LCDIF_D14 */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D14_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D14_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D14_CHANNEL                                     14U   /*!< Signal channel */

/* GPIO_B1_01 (coord B11), LCDIF_D13 */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D13_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D13_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D13_CHANNEL                                     13U   /*!< Signal channel */

/* GPIO_B1_00 (coord A11), LCDIF_D12 */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D12_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D12_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D12_CHANNEL                                     12U   /*!< Signal channel */

/* GPIO_B0_15 (coord E11), LCDIF_D11/BT_CFG[11] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D11_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D11_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D11_CHANNEL                                     11U   /*!< Signal channel */

/* GPIO_B0_14 (coord E10), LCDIF_D10/BT_CFG[10] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D10_PERIPHERAL                                LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D10_SIGNAL                               lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D10_CHANNEL                                     10U   /*!< Signal channel */

/* GPIO_B0_13 (coord D10), LCDIF_D9/BT_CFG[9] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D9_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D9_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D9_CHANNEL                                       9U   /*!< Signal channel */

/* GPIO_B0_12 (coord C10), LCDIF_D8/BT_CFG[8] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D8_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D8_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D8_CHANNEL                                       8U   /*!< Signal channel */

/* GPIO_B0_11 (coord A10), LCDIF_D7/BT_CFG[7] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D7_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D7_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D7_CHANNEL                                       7U   /*!< Signal channel */

/* GPIO_B0_10 (coord D9), LCDIF_D6/BT_CFG[6] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D6_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D6_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D6_CHANNEL                                       6U   /*!< Signal channel */

/* GPIO_B0_09 (coord C9), LCDIF_D5/BT_CFG[5] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D5_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D5_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D5_CHANNEL                                       5U   /*!< Signal channel */

/* GPIO_B0_08 (coord B9), LCDIF_D4/BT_CFG[4] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D4_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D4_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D4_CHANNEL                                       4U   /*!< Signal channel */

/* GPIO_B0_07 (coord A9), LCDIF_D3/BT_CFG[3] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D3_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D3_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D3_CHANNEL                                       3U   /*!< Signal channel */

/* GPIO_B0_06 (coord A8), LCDIF_D2/BT_CFG[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D2_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D2_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D2_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_B0_05 (coord B8), LCDIF_D1/BT_CFG[1] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D1_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D1_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_B0_01 (coord E7), LCDIF_ENABLE */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_ENABLE_PERIPHERAL                             LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_ENABLE_SIGNAL                          lcdif_enable   /*!< Signal name */

/* GPIO_B0_02 (coord E8), LCDIF_HSYNC */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_HSYNC_PERIPHERAL                              LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_HSYNC_SIGNAL                            lcdif_hsync   /*!< Signal name */

/* GPIO_B0_03 (coord D8), LCDIF_VSYNC */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_VSYNC_PERIPHERAL                              LCDIF   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_VSYNC_SIGNAL                            lcdif_vsync   /*!< Signal name */

/* GPIO_B1_15 (coord B14), USB_HOST_PWR/BACKLIGHT_CTL */
/* Routed pin properties */
#define BOARD_INITPINS_BACKLIGHT_CTL_PERIPHERAL                            GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_BACKLIGHT_CTL_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_BACKLIGHT_CTL_CHANNEL                                 31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_BACKLIGHT_CTL_GPIO                                  GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_BACKLIGHT_CTL_GPIO_PIN                                31U   /*!< GPIO pin number */
#define BOARD_INITPINS_BACKLIGHT_CTL_GPIO_PIN_MASK                   (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_BACKLIGHT_CTL_PORT                                  GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_BACKLIGHT_CTL_PIN                                     31U   /*!< PORT pin number */
#define BOARD_INITPINS_BACKLIGHT_CTL_PIN_MASK                        (1U << 31U)   /*!< PORT pin mask */

/* GPIO_AD_B0_11 (coord G10), JTAG_nTRST/J21[3]/INT2_COMBO/LCD_TOUCH_INT/J22[3]/U32[9] */
/* Routed pin properties */
#define BOARD_INITPINS_SE_RST_PERIPHERAL                                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_SE_RST_SIGNAL                                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SE_RST_CHANNEL                                        11U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SE_RST_GPIO                                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SE_RST_GPIO_PIN                                       11U   /*!< GPIO pin number */
#define BOARD_INITPINS_SE_RST_GPIO_PIN_MASK                          (1U << 11U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SE_RST_PORT                                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SE_RST_PIN                                            11U   /*!< PORT pin number */
#define BOARD_INITPINS_SE_RST_PIN_MASK                               (1U << 11U)   /*!< PORT pin mask */

/* GPIO_SD_B0_00 (coord J4), SD1_CMD/J24[6] */
/* Routed pin properties */
#define BOARD_INITPINS_RC_663_SPI_CLK_PERIPHERAL                          LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_RC_663_SPI_CLK_SIGNAL                                 SCK   /*!< Signal name */

/* GPIO_SD_B0_02 (coord J1), SD1_D0/J24[4]/SPI_MOSI/PWM */
/* Routed pin properties */
#define BOARD_INITPINS_RC_633_SPI_MOSI_PERIPHERAL                         LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_RC_633_SPI_MOSI_SIGNAL                                SDO   /*!< Signal name */

/* GPIO_SD_B0_03 (coord K1), SD1_D1/J24[5]/SPI_MISO */
/* Routed pin properties */
#define BOARD_INITPINS_RC_633_SPI_MISO_PERIPHERAL                         LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_RC_633_SPI_MISO_SIGNAL                                SDI   /*!< Signal name */

/* GPIO_SD_B0_01 (coord J3), SD1_CLK/J24[3] */
/* Routed pin properties */
#define BOARD_INITPINS_RC_633_SPI_SSEL_PERIPHERAL                         LPSPI1   /*!< Peripheral name */
#define BOARD_INITPINS_RC_633_SPI_SSEL_SIGNAL                               PCS0   /*!< Signal name */

/* GPIO_AD_B0_03 (coord G11), USB_OTG1_OC/J24[1] */
/* Routed pin properties */
#define BOARD_INITPINS_RC_633_IRQ_PERIPHERAL                               GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_RC_633_IRQ_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RC_633_IRQ_CHANNEL                                     3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RC_633_IRQ_GPIO                                     GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RC_633_IRQ_GPIO_PIN                                    3U   /*!< GPIO pin number */
#define BOARD_INITPINS_RC_633_IRQ_GPIO_PIN_MASK                       (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RC_633_IRQ_PORT                                     GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RC_633_IRQ_PIN                                         3U   /*!< PORT pin number */
#define BOARD_INITPINS_RC_633_IRQ_PIN_MASK                            (1U << 3U)   /*!< PORT pin mask */

/* GPIO_AD_B1_08 (coord H13), AUD_INT/CSI_D9//J35[13]/J22[4] */
/* Routed pin properties */
#define BOARD_INITPINS_RC_633_nPDOWN_PERIPHERAL                            GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_RC_633_nPDOWN_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_RC_633_nPDOWN_CHANNEL                                 24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_RC_633_nPDOWN_GPIO                                  GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_RC_633_nPDOWN_GPIO_PIN                                24U   /*!< GPIO pin number */
#define BOARD_INITPINS_RC_633_nPDOWN_GPIO_PIN_MASK                   (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_RC_633_nPDOWN_PORT                                  GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_RC_633_nPDOWN_PIN                                     24U   /*!< PORT pin number */
#define BOARD_INITPINS_RC_633_nPDOWN_PIN_MASK                        (1U << 24U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_AD_B1_00 (coord J11), I2C1_SCL/CSI_I2C_SCL/J35[20]/J23[6]/U13[17]/U32[4] */
/* Routed pin properties */
#define BOARD_INITI2CPINS_I2C_CLK_PERIPHERAL                              LPI2C1   /*!< Peripheral name */
#define BOARD_INITI2CPINS_I2C_CLK_SIGNAL                                     SCL   /*!< Signal name */

/* GPIO_AD_B1_01 (coord K11), I2C1_SDA/CSI_I2C_SDA/J35[22]/J23[5]/U13[18]/U32[6] */
/* Routed pin properties */
#define BOARD_INITI2CPINS_I2C_SDA_PERIPHERAL                              LPI2C1   /*!< Peripheral name */
#define BOARD_INITI2CPINS_I2C_SDA_SIGNAL                                     SDA   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2CPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init_NFCPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
