/*
 * THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Copyright (C) 2019 Trusted Objects. All rights reserved.
 */

#ifndef _TODRV_SSE_DRIVER_H_
#define _TODRV_SSE_DRIVER_H_

#include "TODRV_SSE_cfg.h"
#include "TOP_vt.h"

#ifdef TODRV_SSE_TOP_ADDRESS
#define TODRV_SSE_TOP_API_ADDRESS TODRV_SSE_TOP_ADDRESS
#define TODRV_SSE_TOP_OFFSET_ADDRESS TODRV_SSE_TOP_ADDRESS
#else
#define TODRV_SSE_TOP_API_ADDRESS &TOP_vt
#define TODRV_SSE_TOP_OFFSET_ADDRESS 0
#endif

#endif /* _TODRV_SSE_DRIVER_H_ */
